export const env = {
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY!,
  WHATSAPP_TOKEN: process.env.WHATSAPP_TOKEN!,
  VERIFY_TOKEN: process.env.VERIFY_TOKEN!,
  PHONE_NUMBER_ID: process.env.PHONE_NUMBER_ID!,

  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  SUPABASE_SERVICE_ROLE_KEY:
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
};